1) Prepare a classification model using SVM for salary data (train)

In [2]:
#load libraries and data set
import numpy as np
import pandas as pd
#!pip install pandas_profiling
from pandas_profiling import ProfileReport

In [3]:
data=pd.read_csv("D:\\DATA SCIENCE\\DATA SCIENCE ASSIGNMENTS\\Assignments\\SVM\\SalaryData_Train.csv",engine='python')
data

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [4]:
profile = ProfileReport(data,title='Pandas Profiling Report',explorative=True)

In [5]:
#profile

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [7]:
data.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [8]:
# check null values
data.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [9]:
#check duplicate records
dup=data.duplicated()
print(dup.sum())
data[dup]

3258


age workclass      education  educationno        maritalstatus  \
326     33   Private      Bachelors           13   Married-civ-spouse   
364     27   Private      Bachelors           13        Never-married   
518     24   Private        HS-grad            9        Never-married   
525     24   Private        HS-grad            9        Never-married   
619     33   Private      Bachelors           13   Married-civ-spouse   
...    ...       ...            ...          ...                  ...   
30110   47   Private        HS-grad            9   Married-civ-spouse   
30118   20   Private        HS-grad            9        Never-married   
30132   22   Private   Some-college           10        Never-married   
30157   40   Private        HS-grad            9   Married-civ-spouse   
30159   22   Private        HS-grad            9        Never-married   

               occupation    relationship    race      sex  capitalgain  \
326       Exec-managerial         Husband   White     Male            0   
364          Craft-repair   Not-in-family   White     Male            0   
518     Handlers-cleaners       Unmarried   Black   Female            0   
525          Craft-repair       Own-child   White     Male            0   
619       Exec-managerial         Husband   White     Male            0   
...                   ...             ...     ...      ...          ...   
30110        Craft-repair         Husband   White     Male            0   
30118   Machine-op-inspct       Own-child   White     Male            0   
30132        Adm-clerical       Own-child   White     Male            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30159        Adm-clerical       Own-child   White     Male            0   

       capitalloss  hoursperweek          native  Salary  
326              0            40   United-States    >50K  
364              0            50   United-States   <=50K  
518              0            40   United-States   <=50K  
525              0            40   United-States   <=50K  
619              0            40   United-States    >50K  
...            ...           ...             ...     ...  
30110            0            40   United-States   <=50K  
30118            0            40   United-States   <=50K  
30132            0            40   United-States   <=50K  
30157            0            40   United-States    >50K  
30159            0            20   United-States   <=50K  

[3258 rows x 14 columns]

In [10]:
#drop the duplicated records
#data1=data.drop_duplicates()

In [11]:
X = data.iloc[:,:-1]

In [12]:
X

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  
0                0            40   United-States  
1                0            13   United-States  
2                0            40   United-States  
3                0            40   United-States  
4                0            40            Cuba  
...            ...           ...             ...  
30156            0            38   United-States  
30157            0            40   United-States  
30158            0            40   United-States  
30159            0            20   United-States  
30160            0            40   United-States  

[30161 rows x 13 columns]

In [13]:
Y = data['Salary']

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [15]:
y = le.fit_transform(Y)

In [16]:
y_train = pd.DataFrame(y)
y_train.value_counts()

0    22653
1     7508
dtype: int64

In [17]:
y_train

0
0      0
1      0
2      0
3      0
4      0
...   ..
30156  0
30157  1
30158  0
30159  0
30160  1

[30161 rows x 1 columns]

# Feature Engineering


In [18]:
#We can calculate the PPS of all the predictors in the dataframe against a target y
import ppscore as pps
pps.predictors(data,"Salary")

x       y       ppscore            case  is_valid_score  \
0     capitalgain  Salary  2.953948e-01  classification            True   
1       education  Salary  2.366993e-01  classification            True   
2     educationno  Salary  2.366993e-01  classification            True   
3     capitalloss  Salary  1.271312e-01  classification            True   
4    relationship  Salary  1.174597e-01  classification            True   
5       workclass  Salary  9.274449e-02  classification            True   
6             age  Salary  2.752510e-02  classification            True   
7    hoursperweek  Salary  2.080733e-02  classification            True   
8          native  Salary  5.812138e-03  classification            True   
9   maritalstatus  Salary  7.704246e-04  classification            True   
10     occupation  Salary  1.254681e-07  classification            True   
11           race  Salary  1.254681e-07  classification            True   
12            sex  Salary  1.254681e-07  classification            True   

         metric  baseline_score  model_score                     model  
0   weighted F1        0.643127     0.748545  DecisionTreeClassifier()  
1   weighted F1        0.643127     0.727598  DecisionTreeClassifier()  
2   weighted F1        0.643127     0.727598  DecisionTreeClassifier()  
3   weighted F1        0.643127     0.688496  DecisionTreeClassifier()  
4   weighted F1        0.643127     0.685045  DecisionTreeClassifier()  
5   weighted F1        0.643127     0.676225  DecisionTreeClassifier()  
6   weighted F1        0.643127     0.652950  DecisionTreeClassifier()  
7   weighted F1        0.643127     0.650552  DecisionTreeClassifier()  
8   weighted F1        0.643127     0.645201  DecisionTreeClassifier()  
9   weighted F1        0.643127     0.643401  DecisionTreeClassifier()  
10  weighted F1        0.643127     0.643127  DecisionTreeClassifier()  
11  weighted F1        0.643127     0.643127  DecisionTreeClassifier()  
12  weighted F1        0.643127     0.643127  DecisionTreeClassifier()

In [19]:
data.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [20]:
# from sklearn.feature_selection import SelectKBest, chi2
# test = SelectKBest(score_func=chi2,k=9)
# fit = test.fit(X,y)
# #summarize score
# fit.scores_   # it gives chi2 values (here choose top 9 feature)

In [21]:
# chi2(X,y)

In [22]:
X_train = X.drop(columns={'native','maritalstatus','race','sex'},axis=1)

In [23]:
X_train

age          workclass    education  educationno          occupation  \
0       39          State-gov    Bachelors           13        Adm-clerical   
1       50   Self-emp-not-inc    Bachelors           13     Exec-managerial   
2       38            Private      HS-grad            9   Handlers-cleaners   
3       53            Private         11th            7   Handlers-cleaners   
4       28            Private    Bachelors           13      Prof-specialty   
...    ...                ...          ...          ...                 ...   
30156   27            Private   Assoc-acdm           12        Tech-support   
30157   40            Private      HS-grad            9   Machine-op-inspct   
30158   58            Private      HS-grad            9        Adm-clerical   
30159   22            Private      HS-grad            9        Adm-clerical   
30160   52       Self-emp-inc      HS-grad            9     Exec-managerial   

         relationship  capitalgain  capitalloss  hoursperweek  
0       Not-in-family         2174            0            40  
1             Husband            0            0            13  
2       Not-in-family            0            0            40  
3             Husband            0            0            40  
4                Wife            0            0            40  
...               ...          ...          ...           ...  
30156            Wife            0            0            38  
30157         Husband            0            0            40  
30158       Unmarried            0            0            40  
30159       Own-child            0            0            20  
30160            Wife        15024            0            40  

[30161 rows x 9 columns]

In [24]:
X_dum = pd.get_dummies(X_train)

In [25]:
X_dum.shape

(30161, 48)

In [26]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_train_norm = SS.fit_transform(X_dum)
X_train_norm

array([[ 0.04277892,  1.12889813,  0.14608503, ..., -0.41690303,
        -0.34523629, -0.22112405],
       [ 0.88026081,  1.12889813, -0.14744712, ..., -0.41690303,
        -0.34523629, -0.22112405],
       [-0.0333558 , -0.4397325 , -0.14744712, ..., -0.41690303,
        -0.34523629, -0.22112405],
       ...,
       [ 1.48933854, -0.4397325 , -0.14744712, ..., -0.41690303,
         2.89656687, -0.22112405],
       [-1.25151126, -0.4397325 , -0.14744712, ...,  2.39863934,
        -0.34523629, -0.22112405],
       [ 1.03253024, -0.4397325 ,  1.88108414, ..., -0.41690303,
        -0.34523629,  4.52234849]])

In [27]:
# Build a model
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [47]:
model = SVC(C=18,kernel='poly',degree=4) # default kernal='rbf' and default panalty C=1 
model.fit(X_train_norm,y_train.values.ravel())
model.score(X_train_norm,y_train.values.ravel())  #check training accuracy

0.8769271575876132

## Grid Search CV

In [29]:
# from sklearn.model_selection import GridSearchCV
# # SVM
# clf = SVC()
# param_grid = [{'kernel':['rbf'],'C':[1.5],'gamma':[0.0009]}]
# gsv = GridSearchCV(clf,param_grid,cv=3)
# gsv.fit(X_train_norm,y)
# print(gsv.best_params_)
# print(gsv.best_score_ )

In [30]:
# Take test file from other notebook
test_df =pd.read_csv("svm_test_file.csv")
test_df

age      workclass      education  educationno          occupation  \
0       25        Private           11th            7   Machine-op-inspct   
1       38        Private        HS-grad            9     Farming-fishing   
2       28      Local-gov     Assoc-acdm           12     Protective-serv   
3       44        Private   Some-college           10   Machine-op-inspct   
4       34        Private           10th            6       Other-service   
...    ...            ...            ...          ...                 ...   
15055   33        Private      Bachelors           13      Prof-specialty   
15056   39        Private      Bachelors           13      Prof-specialty   
15057   38        Private      Bachelors           13      Prof-specialty   
15058   44        Private      Bachelors           13        Adm-clerical   
15059   35   Self-emp-inc      Bachelors           13     Exec-managerial   

         relationship  capitalgain  capitalloss  hoursperweek  0  
0           Own-child            0            0            40  0  
1             Husband            0            0            50  0  
2             Husband            0            0            40  1  
3             Husband         7688            0            40  1  
4       Not-in-family            0            0            30  0  
...               ...          ...          ...           ... ..  
15055       Own-child            0            0            40  0  
15056   Not-in-family            0            0            36  0  
15057         Husband            0            0            50  0  
15058       Own-child         5455            0            40  0  
15059         Husband            0            0            60  1  

[15060 rows x 10 columns]

In [31]:
X_test = test_df.iloc[:,:-1]
y_test = test_df.iloc[:,-1]

In [32]:
X_Dum = pd.get_dummies(X_test)

In [33]:
X_Dum.shape

(15060, 48)

In [34]:
X_test_norm = SS.fit_transform(X_Dum)
X_test_norm

array([[-1.02900513, -1.2165628 , -0.14543845, ...,  2.44381305,
        -0.34187609, -0.21829378],
       [-0.05742253, -0.43489824, -0.14543845, ..., -0.4091966 ,
        -0.34187609, -0.21829378],
       [-0.80479376,  0.73759862, -0.14543845, ..., -0.4091966 ,
        -0.34187609, -0.21829378],
       ...,
       [-0.05742253,  1.1284309 , -0.14543845, ..., -0.4091966 ,
        -0.34187609, -0.21829378],
       [ 0.39100021,  1.1284309 ,  0.562734  , ...,  2.44381305,
        -0.34187609, -0.21829378],
       [-0.2816339 ,  1.1284309 , -0.14543845, ..., -0.4091966 ,
        -0.34187609, -0.21829378]])

In [35]:
y_test = test_df.iloc[:,-1]
y_test

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: 0, Length: 15060, dtype: int64

In [48]:
# model testing 
model.fit(X_test_norm,y_test)

y_pred=model.predict(X_test_norm)
print(y_pred)

acc=accuracy_score(y_test,y_pred)*100
print("Accuracy = ",acc)

confusion_matrix(y_test,y_pred)

[0 0 1 ... 1 0 1]
Accuracy =  88.08764940239044


array([[10805,   555],
       [ 1239,  2461]], dtype=int64)